### ISSUE TITLE
about:settings

### ISSUE THREAD

**Issue by benfrancis** [mozilla-b2g/gecko-tablet#15]
As a user I want to access Settings by typing "about:settings" into the URL bar

**Comment by kskarthik** [comment]
How about a similar command **about:wifi** for wifi too ?

**Comment by Coder206** [comment]
I think we should avoid these sorts of commands by making them easily accessible in a menu. How is the target audience going to remember all this!
@kskarthik I was thinking the same!

**Comment by benfrancis** [comment]
What I imagine is a "Settings" menu item in the browser menu which loads about:settings in the current window. Exactly like about:preferences in desktop Firefox.
