### ISSUE TITLE
View WiFi Networks

### ISSUE THREAD

**Issue by benfrancis** [mozilla-b2g/gecko-tablet#19]
As a user I want to view a list of WiFi networks in the area so I can join one

**Comment by Coder206** [comment]
@benfrancis It would be cool if this could be incorporated in a webpage when you navigate to keep the browser window in focus. (Makes it less feel like you are stuck in one app)

**Comment by benfrancis** [comment]
You mean like about:settings? :) #15

**Comment by Coder206** [comment]
@benfrancis Yes
