### ISSUE TITLE
Battery Indicator

### ISSUE THREAD

**Issue by benfrancis** [mozilla-b2g/gecko-tablet#26]
As a user I want to know my current batter level and when the device is charging

Battery icon in status bar

**Comment by lissyx** [comment]
I'm going to fix this, we really need this soon to avoid battery drainage going in our back

**Comment by lissyx** [comment]
https://github.com/mozilla-b2g/gecko-tablet/pull/56

**Comment by lissyx** [comment]
https://github.com/mozilla-b2g/gecko-tablet/pull/56
