### ISSUE TITLE
View Bookmarks

### ISSUE THREAD

**Issue by benfrancis** [mozilla-b2g/gecko-tablet#28]
As a user I want to see a list of pages I have bookmarked so I can re-visit them

**Comment by Coder206** [comment]
@benfrancis I think folders and categories would add lots of value to the user. Even like having only some visible at certain places. Ex: educational folders in schools

**Comment by Ryuno-Ki** [comment]
Well, personally I prefer the kind [Activity Stream](https://wiki.mozilla.org/Firefox/Activity_Stream) displays my history and bookmarks. I think, the concept of folders and categories does not fit in modern times.

What about tagging bookmarks? Or defining profiles (for school/spare time)?
