### ISSUE TITLE
Web App Suggestions

### ISSUE THREAD

**Issue by benfrancis** [mozilla-b2g/gecko-tablet#31]
As a user I want to see suggestions of web apps as I type into the URL bar

e.g. I type "fa" and see a Facebook icon appear

**Comment by benfrancis** [comment]
It would be great to be able to use this as part of the user study. Maybe we can mock something up for a defined list of sites that we can guide users towards.

**Comment by Ryuno-Ki** [comment]
How do you would order the list? Which criteria?
Recently used? Would need you to store some kind of history.
[Levenshtein-distance](https://en.wikipedia.org/wiki/Levenshtein_distance)? Where do you get the suggestions to match against?

**Comment by benfrancis** [comment]
Ultimately I see this working like search suggestions, using a (potentially third party) service to match against a search index of W3C web app manifests on the web. It could use a standardised interface, perhaps an extension of Open Search.

For the prototype we can create a mock service with some basic listings.
