### ISSUE TITLE
Support for Flatfish

### ISSUE THREAD

**Issue by Ryuno-Ki** [mozilla-b2g/gecko-tablet#35]
Hello,

I have a Flatfish tablet from [TCP campaign](https://wiki.mozilla.org/Firefox_OS/TCP) here. Is it of any use for the purpose of porting B2G to the tablet form factor for you?

**Comment by lissyx** [comment]
The Flatfish has been dead for a long time, I fear there is a lot of work to get it back. Moreover, it is relying on a badly supported (by Gecko) version of Jelly Bean, 4.2. Maybe @tdz ?

**Comment by tdz** [comment]
I had a local copy for flatfish and used to keep it building until
recently. I'd try at least to get it working.

Am 08.06.2016 um 12:18 schrieb lissyx:

**Comment by benfrancis** [comment]
It would be great if we could re-use this hardware in future as it will help contributors who already have one to contribute. However, this isn't a priority for the prototype we're building for the user study which will use the Sony Xperia Z2 Tablet as it has up to date support from AOSP and a much nicer screen!

**Comment by Ryuno-Ki** [comment]
Okay, so I can try it on my own without expecting support from this group. Fine!

I'll report my experience when I'm working on flatfish.

**Comment by tdz** [comment]
I will take a look as soon as I have such a tablet.

If you want to help, you're more than welcome. Flatfish runs the older version of JB, IIRC. Building should generally not be a problem, but as flatfish doesn't have a RIL stack, some of the Bluetooth code is different and occasionally breaks.
