### ISSUE TITLE
Scale UI for device resolution

### ISSUE THREAD

**Issue by benfrancis** [mozilla-b2g/gecko-tablet#38]
Let's try to scale the UI better for the resolution of the Xperia Z2 tablet hardware we're using for the prototype, something like this:

![homescreen-2x](https://cloud.githubusercontent.com/assets/552417/15993929/e50318c2-30ec-11e6-9385-e284ddc3b03e.png)

**Comment by benfrancis** [comment]
To be more precise:

![homescreen_dimensions](https://cloud.githubusercontent.com/assets/552417/16012057/b6984bf4-317f-11e6-92b2-dd4967b7d05f.png)

These should be the dimensions for the Z2 Tablet at a resolution of 1200x1920, which we could treat as 2x size (20px base font size) vs. 1x size (10px base font size) with dimensions set in rem. Perhaps use a media query for a screen width of at least 1200px and reset the based font size there.

**Comment by Ryuno-Ki** [comment]
Media Query would kick in if you switch the tablet from portrait to landscape …

Why rem? [em has its use cases](https://css-tricks.com/rem-global-em-local/), too.

**Comment by benfrancis** [comment]
Fixed by #43 

(the media query was based on pixel density in the end)
