### ISSUE TITLE
Dev mode

### ISSUE THREAD

**Issue by Coder206** [mozilla-b2g/gecko-tablet#46]
It would be great to have FireFox Developer Edition's functionality for mobile embedded in this tablet. I have never encountered a mobile browser that supports this. This would be a great place to set us apart. An affordable tablet for everyone.

**Comment by Ryuno-Ki** [comment]
I assume that would run afoul [the hypothesis](https://wiki.mozilla.org/Connected_Devices/Projects/Project_Tablet#Hypothesis).

**Comment by Coder206** [comment]
@Ryuno-Ki Is this even an active project?

**Comment by Ryuno-Ki** [comment]
Don't know. I'm just following to keep up-to-date about the progress. Project Tablet is part of Connected Devices. I focus on B2G OS.

**Comment by Coder206** [comment]
@Ryuno-Ki Thanks :)

**Comment by benfrancis** [comment]
The main target market for this product is late majority/tech pessimists, not developers. We have to prove the demand in that segment before worrying about power user features. Note that you can use Firefox Developer tools to debug a B2G OS device remotely using remote debugging.
