### ISSUE TITLE
UX Ideas to Replace Buttons

### ISSUE THREAD

**Issue by Coder206** [mozilla-b2g/gecko-tablet#49]
I think those three buttons at the button are a little bit of a cliché
- Slide left to go back
- Slide right to view the tabs vertically (vertical tab center)
- Keep sliding right to go forward
- Bring fingers together for all the windows

**Comment by benfrancis** [comment]
These are exactly the kinds of hard to discover gestures I want to avoid, in favour of interactions with clear visual affordances. The target market for this project is late adopters/tech pessimists. Gestures should only be used in addition to buttons for power users, not instead of them.
