### ISSUE TITLE
Adaptive Interface and Content to the Environnement 

### ISSUE THREAD

**Issue by Coder206** [mozilla-b2g/gecko-tablet#50]
Use a light sensor to adjust the brightness and screen color automatically to suit the lighting and environment.

Inject CSS in websites to modify their content's appearance in a relative fashion to have color constancy (keep the same color just different intensities)

**Comment by Ryuno-Ki** [comment]
Sounds like a use case for [CSS filters](https://developer.mozilla.org/en-US/docs/Web/CSS/filter#brightness%28%29_2) :-)

**Comment by Coder206** [comment]
@Ryuno-Ki Oh yes! :)
