### ISSUE TITLE
Support for Web Extensions

### ISSUE THREAD

**Issue by Coder206** [mozilla-b2g/gecko-tablet#51]
It would be nice to be able to harness some power from the FireFox Marketplace for Web Extensions

**Comment by Ryuno-Ki** [comment]
Could you explain?

The B2G OS team is in the transition process to port Firefox OS (core) apps to Web Extensions.

**Comment by benfrancis** [comment]
> It would be nice to be able to harness some power from the FireFox Marketplace for Web Extensions

The Firefox Marketplace is being discontinued. But Web Extensions could be a valuable way to extend the functionality of the tablet.

> The B2G OS team is in the transition process to port Firefox OS (core) apps to Web Extensions.

That isn't really true. The core system functions were made into chrome and others will become web apps. B2G OS doesn't yet support Web Extensions, but I hope it will :)

**Comment by Ryuno-Ki** [comment]
@benfrancis [wrote](https://github.com/mozilla-b2g/gecko-tablet/issues/51#issuecomment-230318098):

> B2G OS doesn't yet support Web Extensions, but I hope it will :)

I'll let you know when that's the case. Right now B2G OS cares about getting the core functionality again.
