### ISSUE TITLE
More intuitive interface

### ISSUE THREAD

**Issue by Coder206** [mozilla-b2g/gecko-tablet#55]
This adds to my comments at #49, I feel like the concept interfaces that are being demoed resemble a tablet with a browser app. This is not something new. I think there should be a more unique, exclusive and overall better experience in every aspect.

**Comment by Ryuno-Ki** [comment]
I'm afraid this issue description is too vague to derive actions from it.

**Comment by benfrancis** [comment]
Agreed.
