### ISSUE TITLE
Consider changing UA string

### ISSUE THREAD

**Issue by benfrancis** [mozilla-b2g/gecko-tablet#69]
The device has a UA string of:
  Mozilla/5.0 (Tablet; rv:50.0) Gecko/50.0 Firefox/50.0

Mulet has a UA string of:
  Mozilla/5.0 (Mobile; rv:50.0) Gecko/50.0 Firefox/50.0

Because of the "Tablet" token, the device is getting sent desktop versions of websites which look much worse on the tablet than mobile versions. Should we consider changing the UA string to the mobile one for the purposes of the prototype?

**Comment by lissyx** [comment]
We could make use of the dynamic UA feature, which for example points to https://dynamicua.cdn.mozilla.net/0/%7B3c2e2abc-06d4-11e1-ac3b-374f68613e61%7D for b2g

Changing the pref URL general.useragent.updates.url to something we have direct control over

**Comment by lissyx** [comment]
"Tablet" is being set when ro.build.characteristics.

**Comment by benfrancis** [comment]
Done in #79
